/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CouncilDashboardImport } from './routes/council-dashboard'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CouncilDashboardRoute = CouncilDashboardImport.update({
  id: '/council-dashboard',
  path: '/council-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/council-dashboard': {
      id: '/council-dashboard'
      path: '/council-dashboard'
      fullPath: '/council-dashboard'
      preLoaderRoute: typeof CouncilDashboardImport
      parentRoute: typeof rootRoute
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/council-dashboard': typeof CouncilDashboardRoute
  '/': typeof IndexRoute
}

export interface FileRoutesByTo {
  '/council-dashboard': typeof CouncilDashboardRoute
  '/': typeof IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/council-dashboard': typeof CouncilDashboardRoute
  '/': typeof IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/council-dashboard' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/council-dashboard' | '/'
  id: '__root__' | '/council-dashboard' | '/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CouncilDashboardRoute: typeof CouncilDashboardRoute
  IndexRoute: typeof IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  CouncilDashboardRoute: CouncilDashboardRoute,
  IndexRoute: IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/council-dashboard",
        "/"
      ]
    },
    "/council-dashboard": {
      "filePath": "council-dashboard.tsx"
    },
    "/": {
      "filePath": "index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
